### ISSUE TITLE
Broken Link.

### ISSUE THREAD

**Issue by Pradumnasaraf** [allaboutapps/InAppUpdater#9]
## Issue
**link is broken**not able to resolve the broken link, as I am unable to find a working link.

**Screenshot**
![Screenshot 2021-09-13 210442](https://user-images.githubusercontent.com/51878265/133113372-0ccd7e16-a6f5-4b9d-8ddc-c3edb7bb78ca.png)

**Comment by rezwandev** [comment]
@Pradumnasaraf  implementation 'at.allaboutapps.inappupdater:inappupdater:1.2.1'

**Comment by rrsaikat** [comment]
@Pradumnasaraf 
Thank me later! :D
` implementation 'at.allaboutapps.inappupdater:inappupdater:1.2.1'`
